version: '3.0'

services:
  grafana:
    container_name: 'grafana-x-ray-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.1.2}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-x-ray-datasource
      - ./provisioning:/etc/grafana/provisioning
