// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package xray

import (
	"github.com/aws/aws-sdk-go/private/protocol"
)

const (

	// ErrCodeInvalidRequestException for service response error code
	// "InvalidRequestException".
	//
	// The request is missing required parameters or has invalid parameters.
	ErrCodeInvalidRequestException = "InvalidRequestException"

	// ErrCodeResourceNotFoundException for service response error code
	// "ResourceNotFoundException".
	ErrCodeResourceNotFoundException = "ResourceNotFoundException"

	// ErrCodeRuleLimitExceededException for service response error code
	// "RuleLimitExceededException".
	//
	// You have reached the maximum number of sampling rules.
	ErrCodeRuleLimitExceededException = "RuleLimitExceededException"

	// ErrCodeTagrisAccessDeniedException for service response error code
	// "TagrisAccessDeniedException".
	ErrCodeTagrisAccessDeniedException = "TagrisAccessDeniedException"

	// ErrCodeTagrisInternalServiceException for service response error code
	// "TagrisInternalServiceException".
	ErrCodeTagrisInternalServiceException = "TagrisInternalServiceException"

	// ErrCodeTagrisInvalidArnException for service response error code
	// "TagrisInvalidArnException".
	ErrCodeTagrisInvalidArnException = "TagrisInvalidArnException"

	// ErrCodeTagrisInvalidParameterException for service response error code
	// "TagrisInvalidParameterException".
	ErrCodeTagrisInvalidParameterException = "TagrisInvalidParameterException"

	// ErrCodeTagrisPartialResourcesExistResultsException for service response error code
	// "TagrisPartialResourcesExistResultsException".
	ErrCodeTagrisPartialResourcesExistResultsException = "TagrisPartialResourcesExistResultsException"

	// ErrCodeTagrisThrottledException for service response error code
	// "TagrisThrottledException".
	ErrCodeTagrisThrottledException = "TagrisThrottledException"

	// ErrCodeThrottledException for service response error code
	// "ThrottledException".
	//
	// The request exceeds the maximum number of requests per second.
	ErrCodeThrottledException = "ThrottledException"

	// ErrCodeTooManyTagsException for service response error code
	// "TooManyTagsException".
	ErrCodeTooManyTagsException = "TooManyTagsException"
)

var exceptionFromCode = map[string]func(protocol.ResponseMetadata) error{
	"InvalidRequestException":                     newErrorInvalidRequestException,
	"ResourceNotFoundException":                   newErrorResourceNotFoundException,
	"RuleLimitExceededException":                  newErrorRuleLimitExceededException,
	"TagrisAccessDeniedException":                 newErrorTagrisAccessDeniedException,
	"TagrisInternalServiceException":              newErrorTagrisInternalServiceException,
	"TagrisInvalidArnException":                   newErrorTagrisInvalidArnException,
	"TagrisInvalidParameterException":             newErrorTagrisInvalidParameterException,
	"TagrisPartialResourcesExistResultsException": newErrorTagrisPartialResourcesExistResultsException,
	"TagrisThrottledException":                    newErrorTagrisThrottledException,
	"ThrottledException":                          newErrorThrottledException,
	"TooManyTagsException":                        newErrorTooManyTagsException,
}
