{
 "title": "Application Signals: Services",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "appSignalsDatasource", "query": "grafana-x-ray-datasource" },
   { "name": "cloudwatchDatasource", "query": "cloudwatch" },
   {
    "name": "region",
    "query": {}
   },
   {
    "name": "account",
    "query": {}
   },
   {
    "name": "service",
    "query": {}
   },
   {
    "name": "operation",
    "query": {}
   },
   { "name": "operationDimensions" },
   { "name": "dependencyDimensions" },
   { "name": "dependency" },
   { "name": "environment" }
  ]
 },
 "panels": [
  {
   "title": "Application Signals Dashboard",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard helps visualize Application Signals information from AWS.\nFor more information about Application Signals and how to enable it, see the [AWS Application Signals docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html).\n\nTo get started with this dashboard, select the appropriate Application Signals data source, CloudWatch data source, and region in the variables above. You can use the account dropdown to further narrow down the list of services.\n\nUse the hyperlinks in the `List Services` panel to update the board with the Service you are examining, and you can use the links in the collapsed boards below to examine an Operation or Dependency of that service."
   }
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "List Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "accountId": "$account",
     "group": { "GroupARN": "default", "GroupName": "Default" },
     "queryMode": "Services",
     "region": "$region",
     "serviceName": "$service",
     "serviceQueryType": "listServices",
     "serviceString": "$service"
    }
   ]
  },
  {
   "title": "${service:text} Operations Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "Environment": "$environment", "Operation": "*", "Service": "${service:text}" },
     "expression": "REMOVE_EMPTY(SEARCH('{\"ApplicationSignals\", $serviceKeys,\"Operation\"} MetricName=\"Latency\" $serviceDimensions', 'Average', 60))",
     "label": "${PROP('Dim.Operation')} ",
     "metricName": "Latency",
     "namespace": "ApplicationSignals",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "${service:text} Operations Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "Environment": "$environment", "Operation": "*", "Service": "${service:text}" },
     "label": "${PROP('Dim.Operation')} ",
     "metricName": "Error",
     "namespace": "ApplicationSignals",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "${service:text} Operations Fault",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": { "Environment": "$environment", "Operation": "*", "Service": "${service:text}" },
     "label": "${PROP('Dim.Operation')} ",
     "metricName": "Fault",
     "namespace": "ApplicationSignals",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "${service:text} Dependencies Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": {
      "Environment": "$environment",
      "Operation": "*",
      "RemoteOperation": "*",
      "RemoteService": "*",
      "Service": "${service:text}"
     },
     "label": "${PROP('Dim.Operation')} > ${PROP('Dim.RemoteService')} > ${PROP('Dim.RemoteOperation')} ",
     "metricName": "Latency",
     "namespace": "ApplicationSignals",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "${service:text} Dependencies Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": {
      "Environment": "$environment",
      "Operation": "*",
      "RemoteOperation": "*",
      "RemoteService": "*",
      "Service": "${service:text}"
     },
     "metricName": "Error",
     "namespace": "ApplicationSignals",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "${service:text} Dependencies Fault",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "accountId": "$account",
     "dimensions": {
      "Environment": "$environment",
      "Operation": "*",
      "RemoteOperation": "*",
      "RemoteService": "*",
      "Service": "${service:text}"
     },
     "metricName": "Fault",
     "namespace": "ApplicationSignals",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "${service:text} Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "${service:text} Operations",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "group": {
        "GroupARN": "default",
        "GroupName": "Default",
        "InsightsConfiguration": {
         "InsightsEnabled": true,
         "NotificationsEnabled": true
        }
       },
       "queryMode": "Services",
       "region": "$region",
       "serviceName": "$service",
       "serviceQueryType": "listServiceOperations",
       "serviceString": "$service"
      }
     ]
    },
    {
     "title": "${service:text} $operation SLOS",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "accountId": "$account",
       "group": {
        "GroupARN": "default",
        "GroupName": "Default",
        "InsightsConfiguration": {
         "InsightsEnabled": true,
         "NotificationsEnabled": true
        }
       },
       "operationName": "$operation",
       "queryMode": "Services",
       "region": "$region",
       "serviceName": "$service",
       "serviceQueryType": "listServiceLevelObjectives",
       "serviceString": "$service"
      }
     ]
    },
    {
     "title": "${operation} Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "targets": [
      {
       "accountId": "$account",
       "dimensions": { "Environment": "$environment", "Operation": "$operation", "Service": "${service:text}" },
       "metricName": "Latency",
       "namespace": "ApplicationSignals",
       "queryLanguage": "CWLI",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "${operation} Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
     "targets": [
      {
       "accountId": "$account",
       "dimensions": { "Environment": "$environment", "Operation": "$operation", "Service": "${service:text}" },
       "metricName": "Error",
       "namespace": "ApplicationSignals",
       "queryLanguage": "CWLI",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "${operation} Fault",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
     "targets": [
      {
       "accountId": "$account",
       "dimensions": { "Environment": "$environment", "Operation": "$operation", "Service": "${service:text}" },
       "metricName": "Fault",
       "namespace": "ApplicationSignals",
       "queryLanguage": "CWLI",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "${service:text} Dependencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "${service:text} Dependencies",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "group": {
        "GroupARN": "default",
        "GroupName": "Default",
        "InsightsConfiguration": {
         "InsightsEnabled": true,
         "NotificationsEnabled": true
        }
       },
       "queryMode": "Services",
       "region": "$region",
       "serviceName": "$service",
       "serviceQueryType": "listServiceDependencies",
       "serviceString": "$service"
      }
     ]
    },
    {
     "title": "${dependency} Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
     "targets": [
      {
       "accountId": "$account",
       "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"ApplicationSignals\" MetricName=\"Latency\" $dependencyDimensions', 'Average', 60))",
       "metricEditorMode": 1,
       "metricName": "Latency",
       "namespace": "ApplicationSignals",
       "queryLanguage": "CWLI",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "${dependency} Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
     "targets": [
      {
       "accountId": "$account",
       "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"ApplicationSignals\" MetricName=\"Error\" $dependencyDimensions', 'Average', 60))",
       "metricEditorMode": 1,
       "metricName": "Latency",
       "namespace": "ApplicationSignals",
       "queryLanguage": "CWLI",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "${dependency} Fault",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "targets": [
      {
       "accountId": "$account",
       "expression": "REMOVE_EMPTY(SEARCH('Namespace=\"ApplicationSignals\" MetricName=\"Fault\" $dependencyDimensions', 'Average', 60))",
       "metricEditorMode": 1,
       "metricName": "Latency",
       "namespace": "ApplicationSignals",
       "queryLanguage": "CWLI",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}