name: Code Coverage
on:
  pull_request:
    branches-ignore: [dependabot/**]
jobs:
  workflow-call:
    uses: grafana/code-coverage/.github/workflows/code-coverage.yml@v0.1.10
    with:
      frontend-path-regexp: 
      backend-path-regexp: pkg\/(client|datasource)
